spring:
  application:
    name: cv-analisis
    base-url-micro-send: ${BASE_URL_MICRO_SEND:http://localhost:8082}
    base-url-micro-ai: ${BASE_URL_MICRO_AI:http://localhost:8083}
    base-url-micro-extract: ${BASE_URL_MICRO_EXTRACT:http://localhost:8081}


  rabbitmq:
    host: ${HOST_RABBITMQ:localhost}
    port: ${PORT_RABBITMQ:5672}
    username: ${USERNAME_RABBITMQ:blue}
    password: ${PASSWORD_RABBITMQ:blue1234}

  parameters:
    max_Simultaneos_Request: ${MAX_SIMULTANEOUS_REQUESTS:2}